services:
  terraform:
    image: hashicorp/terraform:1.8
    working_dir: /backend/terraform
    volumes:
      - ./terraform:/terraform
    entrypoint: /bin/sh -c "cd /terraform && terraform init && terraform apply -var-file=terraform.tfvars -auto-approve"
  api:
    build: .
    ports:
      - "8080:8080"
