services:
  api:
    build: .
    environment:
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      TOKEN_KEY_URL: ${TOKEN_KEY_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: testdb
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  phppgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
