services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: testdb
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # ここにrootユーザーのパスワードを設定
      MYSQL_DATABASE: testdb        # 作成したいデータベース名
      MYSQL_USER: user            # データベースユーザー名
      MYSQL_PASSWORD: password       # データベースユーザーのパスワード
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: root                    # phpMyAdminで使用するユーザー名
      PMA_PASSWORD: rootpassword        # 上記ユーザーのパスワード
    ports:
      - "5050:80"                        # phpMyAdminにブラウザからアクセスするためのポート

volumes:
  mariadb_data: