services:
  api:
    build: .
    environment:
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      TOKEN_KEY_URL: ${TOKEN_KEY_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
