version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:1.9
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
    entrypoint: ["sh", "-c", "terraform init -upgrade && terraform apply -var-file=terraform.tfvars -auto-approve"]
#   api:
#     # GitHubActionsで自動生成したimage、buildをコメントアウトで動作
#     # image: ghcr.io/yamamoto99/es-writer:main
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: testdb
#     volumes:
#       - db_data:/var/lib/postgresql/data
#       - ./sql:/docker-entrypoint-initdb.d
#   phppgadmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db
# volumes:
#   db_data:
