services:
  terraform:
    image: hashicorp/terraform:1.9
    working_dir: /terraform
    volumes:
      - .:/terraform
    entrypoint: ["sh", "-c", "terraform init -upgrade && terraform apply -var-file=terraform.tfvars -auto-approve"]
