name: build and test
run-name: イメージを生成 🚀
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yamamoto99/es-writer

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: セットアップ Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: コンテナレジストリにログイン
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Compose ビルド
        working-directory: ./backend
        run: docker-compose build

      - name: ビルドされたイメージのリスト表示
        run: docker images

      - name: Docker Compose イメージをタグ付け
        working-directory: ./backend
        run: |
          docker tag $(docker-compose images -q api) ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: 変数の確認
        run: |
          echo 'Current path:'
          pwd

      - name: 環境変数の読み込み
        run: |
          echo "COGNITO_REGION=${{ secrets.COGNITO_REGION }}" >> $GITHUB_ENV
          echo "COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TOKEN_KEY_URL=${{ secrets.TOKEN_KEY_URL }}" >> $GITHUB_ENV
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

      - name: Dockerイメージをプッシュ
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
