name: deploy
run-name: Terraformの実行とEC2へのデプロイ 🚀
on:
  push:
    branches:
      - main
env:
  COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  TOKEN_KEY_URL: ${{ secrets.TOKEN_KEY_URL }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: AWS CLIのインストール
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > private_key && chmod 600 private_key

      - name: SSH into EC2 and deploy
        run: |
          ssh -i private_key  ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          # アプリケーションのデプロイ
          cd /app
          git pull origin main
          
          # Terraformの実行
          cd /home/ec2-user/app/backend/terraform
          terraform init
          terraform apply -auto-approve
          
          # アプリケーションの起動
          docker build -t progate-app .
          docker stop progate-app || true
          docker rm progate-app || true
          docker run -d --name progate-app -p 8080:8080 progate-app
          EOF
